---
- hosts: webservers
  become: true
  tasks:
  - name: Install Java
    command: yum install java-1.8.0-openjdk -y
    command: yum install java-1.8.0-openjdk-devel -y
  - lineinfile:
     path: /etc/profile
     line: 'export JRE_HOME=/usr/lib/jvm/jre'
  - lineinfile:
     path: /etc/profile
     line: 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk'
  - name: ensure a list of packages installed
    yum:
     name: "{{ packages }}"
    vars:
     packages:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
      - tomcat-javadoc
     state: present
  - name: enable service tomcat
    systemd:
     name: tomcat
     enabled: yes
  - name: start service tomcat
  - name: Stop Tomcat
    service:
      name: tomcat8
      state: stopped
  - name: Clean the existing war file
    file:
      path: /root/apache-tomcat-8.5.46/webapps/gameoflife.war
      state: absent    
  - name: Deploy War File
    get_url:
       url: http://18.223.76.84:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /root/apache-tomcat-8.5.46/webapps/gameoflife.war
  - name: Start Tomcat
    service:
      name: tomcat8
      state: started 
   - name: Deploy War File
     get_url:
       url: http://18.223.76.84:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /root/apache-tomcat-8.5.46/webapps/gameoflife.war
    systemd:
     name: tomcat
     state: started
  
  
  

 
 
