---
- hosts: webservers
  become: true
  tasks:
  - name: Install Java
    command: yum install java-1.8.0-openjdk -y
    command: yum install java-1.8.0-openjdk-devel -y
  - lineinfile:
     path: /etc/profile
     line: 'export JRE_HOME=/usr/lib/jvm/jre'
  - lineinfile:
     path: /etc/profile
     line: 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk'
  - name: ensure a list of packages installed
    yum:
     name: "{{ packages }}"
    vars:
     packages:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
      - tomcat-javadoc
     state: present
  - name: enable service tomcat
    systemd:
     name: tomcat
     enabled: yes
  - name: start service tomcat
    systemd:
     name: tomcat
     state: started
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife.war
    register: stat_result
  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://15.206.124.201:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife&p=war&v=LATEST
       dest: /usr/share/tomcat/webapps/gameoflife.war
  - name: Start Tomcat
    service: name=tomcat state=started

 
 
