---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service:
      name: tomcat8
      state: stopped
  - name: Clean the existing war file
    file:
      path: /root/apache-tomcat-8.5.46/webapps/gameoflife.war
      state: absent    
  - name: Deploy War File
    get_url:
       url: http://18.223.76.84:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /root/apache-tomcat-8.5.46/webapps/gameoflife.war
  - name: Start Tomcat
    service:
      name: tomcat8
      state: started 
   - name: Deploy War File
     get_url:
       url: http://18.223.76.84:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /root/apache-tomcat-8.5.46/webapps/gameoflife.war
