---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    shell: /etc/init.d/tomcatstop
  - name: Clean the existing war file
    file:
      path: /apache-tomcat-8.5.51/webapps/gameoflife.war
      state: absent    
  - name: Deploy War File
    get_url:
       url:http://13.233.83.40:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /apache-tomcat-8.5.51/webapps/gameoflife.war
  - name: Start Tomcat
    shell: /etc/init.d/tomcatstart
 
